name: Lab 4 - Automated Containerization

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    outputs:
      mse: ${{ steps.read.outputs.mse }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - run: python scripts/train.py

      - id: read
        run: |
          echo "mse=$(jq .mse outputs/results/metrics.json)" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: outputs/

  deploy:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: model-artifacts
          path: outputs/

      - run: |
          echo "Current MSE: ${{ needs.train.outputs.mse }}"
          echo "Best MSE: ${{ vars.BEST_MSE }}"

          if (( $(echo "${{ needs.train.outputs.mse }} < ${{ vars.BEST_MSE }}" | bc -l) )); then
            echo "2022BCS0194 ---- Model improved"
          else
            echo "2022BCS0194 ---- Metric did not improve"
            exit 0
          fi

      - run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/surya-sanjan-2022bcs0194-wine-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/surya-sanjan-2022bcs0194-wine-api:latest
